Update format.yml

diff --git a/.github/workflows/format.yml b/.github/workflows/format.yml
--- a/.github/workflows/format.yml
+++ b/.github/workflows/format.yml
@@ -15,15 +15,13 @@ jobs:
           git fetch origin ${{ github.event.pull_request.base.ref }}
           git fetch origin pull/${{ github.event.pull_request.number }}/head:${{ github.event.pull_request.head.ref }}
           BASE_COMMIT=$(git rev-parse ${{ github.event.pull_request.base.sha }})
-          COMMIT_FILES=$(git diff --name-only ${BASE_COMMIT})
-          echo "between"
-          COMMIT_FILES_FILTERED=$(echo ${COMMIT_FILES} | grep -E -- '\.cxx|\.h' | grep -i -v LinkDef)
-          echo "between2"
-          if [ $? -eq 1 ]; then
-            exit 0 ;# no files to be checked
+          COMMIT_FILES=$(git diff --name-only ${BASE_COMMIT} | grep -E -- '\.cxx|\.h' | grep -i -v LinkDef) || true ;# avoid failures if nothing is greped
+          if [ "$COMMIT_FILES" == "" ]; then
+            exit 0 ;# nothing to check
           fi
+
           echo "after"
-          RESULT_OUTPUT=$(git-clang-format-8 --commit ${BASE_COMMIT} --diff --binary $(which clang-format-8) ${COMMIT_FILES_FILTERED})
+          RESULT_OUTPUT=$(git-clang-format-8 --commit ${BASE_COMMIT} --diff --binary $(which clang-format-8) ${COMMIT_FILES})
           if [ "$RESULT_OUTPUT" == "no modified files to format" ] || [ "$RESULT_OUTPUT" == "clang-format did not modify any files" ]; then
             exit 0 ;# all good
           else
